### ISSUE TITLE
Add GCP, Firebase, Azure file uploading support

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#17]
We need a function which takes an enum (Azure, GCP, AWS, Firebase) param and generates a preSignedURL to for its cloud storage

**Comment by scoobhidu** [comment]
picking this up @abhishekraj272

**Comment by scoobhidu** [comment]
![image](https://user-images.githubusercontent.com/89660252/210149132-5a01c1ce-60ab-458c-bf60-d4287b1c6b36.png)
which one of these three do you think would be best for generating signedURL in gcp?

**Comment by scoobhidu** [comment]
@uzaxirr @abhishekraj272 ?

**Comment by uzaxirr** [comment]
> ![image](https://user-images.githubusercontent.com/89660252/210149132-5a01c1ce-60ab-458c-bf60-d4287b1c6b36.png) which one of these three do you think would be best for generating signedURL in gcp?

Can you give the reference to these docs??
Are they GCP's Go SDK docs?

**Comment by uzaxirr** [comment]
> ![image](https://user-images.githubusercontent.com/89660252/210149132-5a01c1ce-60ab-458c-bf60-d4287b1c6b36.png) which one of these three do you think would be best for generating signedURL in gcp?

The first one where we use the private key which is obtained from the console

**Comment by uzaxirr** [comment]
The Private Key and Acess ID would be stored in environment variables. The snippet below is an example.

```go
// Set the bucket and object names.
bucketName := "my-bucket"
objectName := "my-object"

// Set the signed URL expiration time to one hour from now.
expirationTime := time.Now().Add(time.Hour).Unix()

// Get the private key and access ID from environment variables.
privateKey := os.Getenv("PRIVATE_KEY")
accessID := os.Getenv("ACCESS_ID")

// Set the signed URL options.
opt := &storage.SignedURLOptions{
	GoogleAccessID: accessID,
	PrivateKey:     []byte(privateKey),
	Method:         "GET",
	Expires:        expirationTime,
	ContentType:    "application/octet-stream",
}

// Create the signed URL.
signedURL, err := storage.SignedURL(bucketName, objectName, opt)
if err != nil {
	// Handle error.
	return
}
```

**Comment by uzaxirr** [comment]
@loyaltytrooper  do let me know if you are ready to take this up, i'll assign this to you

**Comment by abskrj** [comment]
Done
