### ISSUE TITLE
Add an endpoint for generating cloud storage pre-signed url

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#2]
We need an endpoint which generates the pre-signed URL for uploading video objects to bucket directly.
Also the cloud-storage should be flexible, like using AWS S3, Google Cloud or Azure can be depending upon the configuration.

Also generate a video Id (7-8 chars) and return it in response

Eg: [AWS](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/s3-example-presigned-urls.html), [Google Cloud](https://cloud.google.com/storage/docs/access-control/signed-urls#:~:text=Options%20for%20generating%20a%20signed%20URL,-Cloud%20Storage%20supports&text=Simply%20specify%20Cloud%20Storage%20resources,of%20generating%20the%20signed%20URL.), [Azure](https://stackoverflow.com/questions/55233010/azure-blob-storage-pre-signed-url-features)

**Comment by uzaxirr** [comment]
Hey, This looks like something i can help out with. Can you please assign the issue to me so that I can start working on it.

Just one question, Am i supposed to use the Go SDK provided by these services or just have to use the simple API calls to achieve this?

**Comment by abskrj** [comment]
It would be better to use the SDK as we will be using their more functions while adding more features.

**Comment by uzaxirr** [comment]
> It would be better to use the SDK as we will be using their more functions while adding more features.

Sure thing, Thanks for the clarification
