### ISSUE TITLE
Generate thumbnail from Video and Save it to cloud storage

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#24]
We need to write a function which takes a timestamp (HH:MM:SS string) and generates a thumbnail from the video and stores in output/video_id folder (as for now)

**Comment by Catalyst-47** [comment]
@abhishekraj272 Can you assign this to me?

**Comment by abskrj** [comment]
@Catalyst-47 can you take up #35, PR for this issue has be already raised

**Comment by Catalyst-47** [comment]
@abhishekraj272  sure works
