### ISSUE TITLE
Create an endpoint to publish event on Kafka

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#3]
We need an endpoint which takes the below object in body and publishes an event in Kafka (Kafka URI present in environment variable, if not present throw Err while starting service).

```json
{
  "video": {
    "id": "string",
    "src": "string",
    "type": "mp4"
  }
}
```

**Comment by vivek378521** [comment]
@abhishekraj272 Can I work on this?

**Comment by abskrj** [comment]
yes @vivek378521

**Comment by vivek378521** [comment]
@abhishekraj272 I have raised a PR: https://github.com/ZeStream/zestream-server/pull/11 

is it in the right direction? Please suggest any changes that you want me to make.

**Comment by abskrj** [comment]
yes, looks good :)

also added few comments

**Comment by abskrj** [comment]
Merged https://github.com/ZeStream/zestream-server/pull/11
