### ISSUE TITLE
Add watermark while generating multi-bitrate video

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#35]
**Is your feature request related to a problem? Please describe.**
We need to have a feature to add watermark to the video while generating the multi-bitrate video. The image will be present in downloads/directory and the filePath will be given, checkout service/dash.go for more details.

**Describe the solution you'd like**
Image file is present in `downloads/` folder, and the `(x,y)` coordinates will be passed to function, and inject the image in all the bitrate videos at the given bitrate.

**Comment by Catalyst-47** [comment]
@abhishekraj272 can you please assign this to me?

**Comment by abskrj** [comment]
@Catalyst-47 done

**Comment by Catalyst-47** [comment]
@abhishekraj272
The output generated after running the test file is not playable
Is this expected behaviour?

**Comment by abskrj** [comment]
Yes, expected

To test it, copy the path of .mpd file
Google how to play video from network stream in VLC

or just google how to run mpd file in vlc

**Comment by Catalyst-47** [comment]
got it
thanks!
