### ISSUE TITLE
Exit inside non-main function

### ISSUE THREAD

**Issue by uzaxirr** [ZeStream/zestream-server#40]
## Description
Packages exposing functions that can stop program execution by exiting are hard to reuse. Program exits in functions other than main() or init() are not encouraged.

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ZeStream/zestream-server/issue/RVV-A0003/occurrences/](https://deepsource.io/gh/ZeStream/zestream-server/issue/RVV-A0003/occurrences/)

<img width="958" alt="Screenshot 2023-01-03 at 10 35 00 AM" src="https://user-images.githubusercontent.com/72073401/210302692-7795ca83-2511-4919-92a8-5fd7fa863ed3.png">

## Solution 
calls to `log.Fatal` should be only in `main()` or `init()` functions. So a possible solution for this could be replacing `log.Fatal` with an Error log level

**Comment by Missing-Parallax** [comment]
I want to work on this

**Comment by akshat2602** [comment]
Hey @Missing-Parallax are you still working on this? If not I'd like to pick this up :)

**Comment by Missing-Parallax** [comment]
Sure Akshat, u can take it.

**Comment by uzaxirr** [comment]
Hey @akshat2602
I've assigned the issue to you!
