### ISSUE TITLE
Use of `net/http`'s `ListenAndServe` function has no support for setting timeouts

### ISSUE THREAD

**Issue by uzaxirr** [ZeStream/zestream-server#41]
## Description
HTTP timeouts are necessary to expire inactive connections and failing to do so might make the application vulnerable to attacks like slowloris which work by sending data very slow, which in case of no timeout will keep the connection active eventually leading to a denial-of-service (DoS) attack.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ZeStream/zestream-server/issue/GO-S2114/occurrences/](https://deepsource.io/gh/ZeStream/zestream-server/issue/GO-S2114/occurrences/)

<img width="782" alt="Screenshot 2023-01-03 at 10 42 12 AM" src="https://user-images.githubusercontent.com/72073401/210303157-7f6bb67f-306b-4813-9e65-99d39b6d4133.png">

## Solution
A possible solution could be

```go
server := &http.Server{
    Addr:         port,
    ReadTimeout:  time.Duration(timeout) * time.Second,
    WriteTimeout: time.Duration(timeout) * time.Second,
}

err := server.ListenAndServe()
```

**Comment by vivek378521** [comment]
Have made some changes to the main.go file 
Please review: https://github.com/ZeStream/zestream-server/pull/45/

Do suggest if any more changes need to be made @uzaxirr

**Comment by vivek378521** [comment]
@uzaxirr there was some rebase issue so resolved your comments and created a new PR: https://github.com/ZeStream/zestream-server/pull/46

Apologies for the older PR. have also attached the test screenshot to the PR

**Comment by uzaxirr** [comment]
closed via https://github.com/ZeStream/zestream-server/pull/46
