### ISSUE TITLE
Unsafe defer of `os.Close`

### ISSUE THREAD

**Issue by uzaxirr** [ZeStream/zestream-server#42]
## Description
Calling `os.Close` on an `io.Closer` may return an error, and ignoring the same might result in a data loss.

## Occurrences
There are 3 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ZeStream/zestream-server/issue/GO-S2307/occurrences/](https://deepsource.io/gh/ZeStream/zestream-server/issue/GO-S2307/occurrences/)
<img width="943" alt="Screenshot 2023-01-03 at 10 49 10 AM" src="https://user-images.githubusercontent.com/72073401/210303597-5f00b2b3-d367-487a-bfcc-5f499c9429ac.png">

### Bad Practice 

```go
package main

import (
    "fmt"
    "os"
)

func foo() error {
    f, err := os.Create("/tmp/test.txt")
    if err != nil {
        return err
    }
    defer f.Close()

    return fmt.Fprint(f, "Hello World")
}
```

### Recommend

```go
package main

import (
    "fmt"
    "os"
)

func foo() error {
    f, err := os.Create("/tmp/test.txt")
    if err != nil {
        return err
    }

    err = fmt.Fprint(f, "Hello World")
    if err != nil {
        return err
    }

    return f.Close()
}
```

```go
package main

import (
    "fmt"
    "os"
)

func foo() error {
    f, err := os.Create("/tmp/test.txt")
    if err != nil {
        return err
    }
    defer f.Close()

    err = fmt.Fprint(f, "Hello World")
    if err != nil {
        return err
    }

    return f.Sync()
}
```

**Comment by akshay1027** [comment]
I am working on this @uzaxirr @abhishekraj272. I have recently started learning Go and using this repo to learn simultaneously!
