### ISSUE TITLE
Random number generator seed doesn't have enough entropy

### ISSUE THREAD

**Issue by uzaxirr** [ZeStream/zestream-server#43]
## Description
As `math/rand` uses a statistical random number generator, using a low entropy seed (such as constants and the current system time) may allow an attacker to predict what the following number generated is.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/ZeStream/zestream-server/issue/GO-S1033/occurrences/](https://deepsource.io/gh/ZeStream/zestream-server/issue/GO-S1033/occurrences/)
<img width="587" alt="Screenshot 2023-01-03 at 10 53 17 AM" src="https://user-images.githubusercontent.com/72073401/210303876-f873c519-74b4-45fe-8970-60e6850bf013.png">

**Comment by vivek378521** [comment]
This package generates crc64 hash and will enable higher entropy. https://pkg.go.dev/hash/crc64 

I can fix this if the approach sounds okay to you. @uzaxirr

**Comment by vivek378521** [comment]
Hey @uzaxirr  Any thoughts on the above comment? Thanks!

**Comment by vivek378521** [comment]
Hey @uzaxirr  Any thoughts on the above comment? Thanks!

**Comment by abskrj** [comment]
you can pick this up @vivek378521

**Comment by vivek378521** [comment]
@abhishekraj272 I have raised the PR: https://github.com/ZeStream/zestream-server/pull/50

Also added a simple test to check if the value is 8 digits or not. The test passed hence the PR was raised.

**Comment by abskrj** [comment]
Fixed with #50
