### ISSUE TITLE
Document setting up Cloud Storage

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#47]
**Is your feature request related to a problem? Please describe.**
Documentation

**Describe the solution you'd like**
As now we have function to upload the folder directly, there should be a doc when people can read and easily understand, how to setup GCP/Azure/AWS.

**Comment by Shofiya2003** [comment]
Can i work on the documentation now?

**Comment by abskrj** [comment]
Sure @Shofiya2003

**Comment by Shofiya2003** [comment]
Do you want me to use godoc for documentation of the function? 
How should I start with the documentation?

**Comment by abskrj** [comment]
you can write it in a markdown file in `docs/` folder

**Comment by Shofiya2003** [comment]
Okay. On it

**Comment by abskrj** [comment]
hey @Shofiya2003, let me know if you are free, need  help in setting up azure

**Comment by Shofiya2003** [comment]
sure how can i help?
@abhishekraj272

**Comment by abskrj** [comment]
got it fixed, can you review the PR did minor change in Azure client #60 
@Shofiya2003

**Comment by abskrj** [comment]
also sent you repo invite, wasn't able to tag on PR

**Comment by Shofiya2003** [comment]
sure

**Comment by Shofiya2003** [comment]
do we really need a documentation to set up cloud storage accounts as the platforms already has guides to do the same ? @abhishekraj272 @uzaxirr

**Comment by abskrj** [comment]
We dont need to create a whole doc, just a simple markdown file with which
env var to set in .env file to run the server would be enough

**Comment by uzaxirr** [comment]
> do we really need a documentation to set up cloud storage accounts as the platforms already has guides to do the same ? @abhishekraj272 @uzaxirr

I think you misunderstood the issue here, We don't want docs on how to set up storage on these cloud platform. Instead we want on how to configure those platform for ZeStream.

**Comment by Shofiya2003** [comment]
Got it
