### ISSUE TITLE
Add docker support 

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#6]
We need to add docker support, using a single command, it should deploy an instance on docker

**Comment by SamantaTarun** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by abskrj** [comment]
@tarunsamanta2k20 working?

**Comment by akhilambati** [comment]
hi @abhishekraj272 , as i see you have unassigned i want to work on it.
can you please share the requirement for docker image like what ports to expose and do we need any mounts on to host etc...

Thanks,
Akhil

**Comment by abskrj** [comment]
@akhilambati you can read requirements in this PR #10

**Comment by abskrj** [comment]
also can we have rebbitmq deployed on the kube along with zestream?

**Comment by akshat2602** [comment]
Can I work on this?

**Comment by abskrj** [comment]
Lets wait for Akhil, till then you can pick up any other tasks

**Comment by akhilambati** [comment]
> also can we have rebbitmq deployed on the kube along with zestream?

sure will work on this

**Comment by akshat2602** [comment]
Hey @akhilambati are you still working on this issue? If not, can I pick this up?

**Comment by abskrj** [comment]
hey @akshat2602, you can pick this up

**Comment by akhilambati** [comment]
hey @abhishekraj272  @akshat2602 sorry for not replying back on time, was busy in production release

please find the PR --> https://github.com/ZeStream/zestream-server/pull/65

**Comment by abskrj** [comment]
Added in #68
