### ISSUE TITLE
Add Azure and GCP support for pre-signing url

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#63]
**Is your feature request related to a problem? Please describe.**
Its a feature

**Describe the solution you'd like**
Currently, we can only generate AWS pre signed url, we should support GCP and Azure also.

**Describe alternatives you've considered**
Add support for GCP and Azure also

**Comment by vivek378521** [comment]
In which file are we generating the AWS pre signed URL?

**Comment by abskrj** [comment]
Added GCP support, Azure is missing
