### ISSUE TITLE
Write unit tests for functions

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#8]
We need to write UTs for all the functions, whose UTs are not written yet.

You can even raise PR with at least 1 UT of a function.

**Comment by SamantaTarun** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by abskrj** [comment]
@tarunsamanta2k20 still working?

**Comment by SamantaTarun** [comment]
@abhishekraj272 I am busy with my own work. Please assign it to someone else.

**Comment by aloner-pro** [comment]
Can you show some examples where unit tests are already written?

**Comment by abskrj** [comment]
@aloner-pro https://www.digitalocean.com/community/tutorials/how-to-write-unit-tests-in-go-using-go-test-and-the-testing-package

**Comment by abskrj** [comment]
Let me know if you are working on it, will assign this to you

**Comment by uzaxirr** [comment]
@aloner-pro 
[This](https://circleci.com/blog/gin-gonic-testing/) is also a good reference for that same, Do let us know if you doesn’t find this issue suitable for you

**Comment by aloner-pro** [comment]
Currently looking into it.

**Comment by uzaxirr** [comment]
> Currently looking into it.

I'll be taking this up as it needs to be done on priority and it also acts as an blocker for #16

**Comment by uzaxirr** [comment]
closed via #21
