### ISSUE TITLE
Add API documentation using Swagger or Postman

### ISSUE THREAD

**Issue by abskrj** [ZeStream/zestream-server#9]
Either integrate SwaggerUI in Go Gin or write the API doc in Postman.

Before starting, do comment which method(Swagger/Postman) you will be using and Why?

**Comment by tarunsamanta2k20** [comment]
I would like to contribute to this issue. Please assign it to me. I will do in both ways. Swagger provides better ui and additional endpoints. So swagger preferred.

**Comment by SreehariJayaraj** [comment]
can I work on this @abhishekraj272 , i am thinking of integrating swagger for docs.

**Comment by abskrj** [comment]
@sreehari2003 yeah
